Digital Reader Breadboard tests
fs-feup/el-sw pull request #21
Opened 2024-04-05 14:13 UTC by andrelds11

2024-04-05 15:30 UTC, marhcouto requested changes

2024-04-05 15:30 UTC, marhcouto commented on master/include/comm/message.hpp
> +#pragma once
What is this?

2024-04-05 18:22 UTC, andrelds11 commented
Fixed main issues from master refactor. Need to test with breadboard. The lwss should need a refactor, but it needs testing

2024-04-07 11:22 UTC, marhcouto approved these changes

2024-04-07 11:22 UTC, merged