Integration Tests
fs-feup/el-sw pull request #25
Opened 2024-04-10 14:19 UTC by andrelds11

2024-04-14 21:45 UTC, marhcouto requested changes
Sorry for taking so long. Overall ok but tests need further documentation. Moreover, I don't think these were very thought through, we can discuss this tomorrow further

2024-04-29 02:30 UTC, andrelds11 commented on master/include/comm/communicator.hpp
> +    _systemData->sensors._right_wheel_rpm = right_wheel_rpm;
consistency

2024-04-30 15:02 UTC, marhcouto requested changes
We should talk about most of these comments. Main topics:
- the unit tests are giving me headaches
- a bit better documentation on the integration tests
- the errors mentioned
- not using function (to_ready) every time you can

2024-05-02 10:33 UTC, andrelds11 commented on master/test/test_integration/test_integration.cpp
> +    sd.digitalData.watchdog_state = false;
Watchdog needs to go low in the initial checkup sequence

2024-05-02 10:33 UTC, andrelds11 commented on master/test/test_integration/test_integration.cpp
> +*/
Off to ready success transition with no other conditions or restraints

2024-05-02 10:34 UTC, andrelds11 commented on master/test/test_integration/test_integration.cpp
> +void test_off_to_ready_wayback() {
It doesn't. The test is to validate it doesn't happen anymore. Changed the name slightly to make it clearer

2024-05-02 10:37 UTC, andrelds11 commented on master/test/test_integration/test_integration.cpp
> +    communicator.resStateCallback(msg);
Communicator is always used when possible for double validation (redundancy), maybe just with the exception of timestamps. Digital Data is always changed directly to do evaluate it with no breadboard inputs

2024-05-02 10:39 UTC, andrelds11 commented on master/test/test_integration/test_integration.cpp
> +    TEST_ASSERT_EQUAL(State::AS_DRIVING, as_state.state); // still within threshold, okay
Unit tests for the checkupmanager specific transitions are in the checkupmanager tests already

2024-05-02 10:42 UTC, andrelds11 commented on master/test/test_integration/test_integration.cpp
> +    communicator.c1Callback(hydraulic_msg);
Included in the initial checkup. Necessary for it to be ready. Will add a comment on that

2024-05-02 10:43 UTC, andrelds11 commented on master/test/test_integration/test_integration.cpp
> +    uint8_t hydraulic_msg[] = {HYDRAULIC_LINE, 0xf8, 0x00};
Should I use decimals? What is the idea?

2024-05-06 10:05 UTC, marhcouto approved these changes

2024-05-06 10:10 UTC, marhcouto commented
I approved but the steering angle from steering's ID is wrong, it is 0x295D and it is an extended ID. Consult the PR in ROS-CAN if you need to check how it is read

2024-05-12 22:20 UTC, andrelds11 commented
> I approved but the steering angle from steering's ID is wrong, it is 0x295D and it is an extended ID. Consult the PR in ROS-CAN if you need to check how it is read

Sorry, I didn't notice this. I changed the id, from what I saw in the other rep, it is normally read so I just changed the id, can you confirm this?

2024-05-14 17:34 UTC, merged